# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=[r'D:\Apps\monitoring-roll-machine\monitoring-roll-machine'],
    binaries=[],
    datas=[
        ('monitoring/ui/assets', 'monitoring/ui/assets'),
        ('monitoring/config.json', 'monitoring'),
        ('requirements.txt', '.'),
        ('LICENSE.txt', '.'),
        ('README.md', '.'),
        ('SUPABASE_SCHEMA.sql', '.'),
        ('BATCH_FEATURE_README.md', '.'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtPrintSupport',
        'pyqtgraph',
        'pyserial',
        'serial.tools.list_ports',
        'python-dotenv',
        'yaml',
        'appdirs',
        'qrcode',
        'PIL',
        'PIL.Image',
        'matplotlib',
        'matplotlib.backends.backend_qtagg',
        'numpy',
        'pandas',
        'requests',
        'openpyxl',
        'supabase',
        'supabase.auth',
        'supabase.client',
        'postgrest',
        'realtime',
        'storage3',
        'httpx',
        'anyio',
        'h11',
        'httpcore',
        'monitoring',
        'monitoring.ui',
        'monitoring.ui.main_window',
        'monitoring.ui.monitoring_view',
        'monitoring.ui.product_form',
        'monitoring.ui.settings_dialog',
        'monitoring.ui.connection_settings',
        'monitoring.ui.logging_table_widget',
        'monitoring.ui.print_preview',
        'monitoring.ui.printer_utils',
        'monitoring.ui.batch_summary_dialog',
        'monitoring.monitor',
        'monitoring.serial_handler',
        'monitoring.config',
        'monitoring.logging_utils',
        'monitoring.logging_table',
        'monitoring.session',
        'monitoring.exporter',
        'monitoring.parser',
        'monitoring.version',
        'monitoring.batch_manager',
        'monitoring.supabase_client',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MonitoringRollMachine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='monitoring/ui/assets/icon.ico'
)
